import React from 'react';
import { Link } from 'react-router-dom';
import { LegalPage, LegalSection } from '../components/LegalPage';
import { SUPPORT_EMAIL, LEGAL_ENTITY, LEGAL_ADDRESS, LEGAL_JURISDICTION, LEGAL_UPDATED } from '../lib/constants';

export const Terms = () => (
  <LegalPage kicker="Terms of service" title="The" highlight="agreement" updated={LEGAL_UPDATED}>
    <LegalSection title="1. Who this is between">
      <p>
        These terms are between {LEGAL_ENTITY} ({LEGAL_ADDRESS}) — “we”, “GymSetu” — and the gym or
        business that subscribes — “you”. By creating an account or paying a subscription fee, you
        accept them.
      </p>
    </LegalSection>

    <LegalSection title="2. What GymSetu does">
      <p>
        GymSetu is software for running a gym: members, membership plans, payments and dues,
        attendance, reports, and optional AI and WhatsApp features. It is provided as a service over
        the internet; we host it and update it.
      </p>
      <p>
        We are a software provider. We are not a party to the relationship between you and your
        members, we do not collect your members’ fees, and we are not responsible for what you agree
        with them.
      </p>
    </LegalSection>

    <LegalSection title="3. Your account">
      <p>
        You are responsible for what happens under your account, including logins you create for your
        trainers and members. Keep credentials private. Tell us promptly if you think an account has
        been compromised.
      </p>
      <p>You must be at least 18 and able to enter a contract on behalf of your business.</p>
    </LegalSection>

    <LegalSection title="4. Your members’ data — your responsibility">
      <p>
        This is the clause that matters most, so it is not buried. When you enter a member’s details,
        <strong className="text-bone"> you decide what is collected and why; we process it on your
        instructions.</strong> Under India’s DPDP Act, that makes you responsible for having a lawful
        basis and for giving your members notice.
      </p>
      <p>
        Concretely: tell your members their data is held in GymSetu, get consent where required, get
        guardian consent for anyone under 18, and only record what you actually need. If a member asks
        you to correct or delete their record, you can do it yourself in the app.
      </p>
    </LegalSection>

    <LegalSection title="5. Fees and billing">
      <p>
        Plans and prices are on our <Link className="text-flame hover:underline" to="/pricing">Pricing</Link> page.
        Fees are payable in advance for the billing period you choose and are processed by PayU.
      </p>
      <p>
        Prices may change; we will give existing subscribers at least 30 days’ notice by email before a
        change affects them, and you can cancel instead of accepting it.
      </p>
      <p>
        Fees are non-refundable. Cancellation and the narrow cases where we do refund are set out in the{' '}
        <Link className="text-flame hover:underline" to="/refund">Refund Policy</Link>, which forms part of these terms.
      </p>
    </LegalSection>

    <LegalSection title="6. Acceptable use">
      <p>Don’t use GymSetu to break the law, send spam or unsolicited marketing to your members, upload malware, or store data you have no right to hold.</p>
      <p>Don’t attempt to access another gym’s data, probe or attack the service, or resell it as your own without a written agreement with us.</p>
      <p>Reasonable use is assumed. If your usage threatens the service for everyone else, we will contact you before taking any action.</p>
    </LegalSection>

    <LegalSection title="7. Availability">
      <p>
        We work to keep GymSetu available and we back up your data nightly. We do not offer a uptime
        guarantee or service credits, and we will not pretend otherwise: the service can go down for
        maintenance, or because something breaks.
      </p>
      <p>Your gym should be able to operate through a short outage. Do not build a process that fails if the app is unreachable for an hour.</p>
    </LegalSection>

    <LegalSection title="8. AI features">
      <p>
        AI-generated content — workout suggestions, diet plans, summaries — is generated by a
        third-party model and can be wrong. It is not medical, nutritional, legal or financial advice.
        Review it before acting on it or giving it to a member. You remain responsible for what you
        pass on.
      </p>
    </LegalSection>

    <LegalSection title="9. Ownership of the software">
      <p>
        GymSetu is owned and operated by {LEGAL_ENTITY}. The software, its name, logo and design are
        our intellectual property and all rights are reserved. Your subscription buys the right to use
        GymSetu to run your gym — it does not transfer ownership of any part of it.
      </p>
      <p>
        You may not copy, resell, reverse-engineer or white-label GymSetu without a written agreement
        with us.
      </p>
    </LegalSection>

    <LegalSection title="10. Your data belongs to you">
      <p>
        You own your gym’s data. We claim no ownership of it and will not sell it. We use it only to
        run the service for you, as described in the{' '}
        <Link className="text-flame hover:underline" to="/privacy">Privacy Policy</Link>.
      </p>
      <p>You can ask us for an export of your data at any time while your account is active, and we will provide it in a common format.</p>
    </LegalSection>

    <LegalSection title="11. Ending it">
      <p>You can cancel at any time — see the <Link className="text-flame hover:underline" to="/refund">Refund Policy</Link>.</p>
      <p>
        We may suspend or end an account that breaches these terms, or where fees are unpaid. Except in
        cases of serious misuse, we will warn you first and give you a chance to fix it. If we end your
        account without cause, we will refund the unused portion of the period you have paid for.
      </p>
    </LegalSection>

    <LegalSection title="12. Liability">
      <p>
        GymSetu is provided “as is”. To the extent the law allows, our total liability to you for any
        claim is limited to the fees you paid us in the 12 months before it arose.
      </p>
      <p>
        We are not liable for indirect or consequential losses — lost profits, lost business or lost
        goodwill. Nothing here limits liability that cannot lawfully be limited, including for fraud.
      </p>
    </LegalSection>

    <LegalSection title="13. Governing law">
      <p>These terms are governed by the laws of India. The courts at {LEGAL_JURISDICTION} have exclusive jurisdiction.</p>
    </LegalSection>

    <LegalSection title="14. Changes">
      <p>
        We may update these terms. If a change materially affects you, we will email you at least 30
        days beforehand. Continuing to use GymSetu after that means you accept the new terms.
      </p>
      <p>Questions: <a className="text-flame hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
    </LegalSection>
  </LegalPage>
);
